workflows:
  release-workflow:
    name: Yditonton CI/CD Release
    # Kita hapus instance_type karena ternyata Codemagic HANYA menggratiskan mesin Mac mini (M1/M2) untuk akun Personal Free Tier.
    environment:
      flutter: stable
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: deploy
          include: true
          source: true
    scripts:
      - name: Get All Dependencies
        script: |
          # Install dependensi untuk root dan semua modul menggunakan subshell agar direktori tidak nyasar
          flutter pub get
          (cd core && flutter pub get)
          (cd search && flutter pub get)
          (cd about && flutter pub get)
          (cd movie && flutter pub get)
          (cd tv && flutter pub get)
          
      - name: Run Unit Tests
        script: |
          # Jalankan testing secara berurutan (--concurrency=1) agar database SQLite tidak bentrok (database locked/disk I/O error) antar-file test
          (cd core && flutter test --concurrency=1)
          (cd search && flutter test --concurrency=1)
          (cd movie && flutter test --concurrency=1)
          (cd tv && flutter test --concurrency=1)
          
      - name: Build Android APK
        script: |
          # Membangun file .apk dalam mode release
          flutter build apk --release
          
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
