// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRzTaBPHwGhvcbpDJJtIPn_RqWAeo-Owc',
    appId: '1:25839825483:web:51f0958f7f505227d653ce',
    messagingSenderId: '25839825483',
    projectId: 'dfe-yditonton',
    authDomain: 'dfe-yditonton.firebaseapp.com',
    storageBucket: 'dfe-yditonton.firebasestorage.app',
    measurementId: 'G-3EK2T1Z627',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN3QL3G97r4RslNw-RQUIFiMvW6MixxvY',
    appId: '1:25839825483:android:6cb436d7ff83d663d653ce',
    messagingSenderId: '25839825483',
    projectId: 'dfe-yditonton',
    storageBucket: 'dfe-yditonton.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsDvJIBC6Y-97z2szfL_A25_V3AJtS65Q',
    appId: '1:25839825483:ios:f87383200f778465d653ce',
    messagingSenderId: '25839825483',
    projectId: 'dfe-yditonton',
    storageBucket: 'dfe-yditonton.firebasestorage.app',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
