name: Flutter CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.x' # Or whatever your version is, but v2 auto downloads latest if omitted, but safe to leave
        channel: 'stable'

    - name: Get dependencies (Root)
      run: flutter pub get

    - name: Get dependencies (Core)
      run: cd core && flutter pub get

    - name: Get dependencies (Search)
      run: cd search && flutter pub get
      
    - name: Get dependencies (About)
      run: cd about && flutter pub get

    - name: Get dependencies (Movie)
      run: cd movie && flutter pub get

    - name: Get dependencies (TV)
      run: cd tv && flutter pub get

    - name: Run Tests (Core)
      run: cd core && flutter test

    - name: Run Tests (Search)
      run: cd search && flutter test

    - name: Run Tests (Movie)
      run: cd movie && flutter test

    - name: Run Tests (TV)
      run: cd tv && flutter test
